-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.7
-- Mon Jun 19 17:14:24 2017

-- parameterized module component declaration
component ECP5U_PLL_2
    port (CLKI: in  std_logic; RST: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : ECP5U_PLL_2
    port map (CLKI=>__, RST=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, LOCK=>__);
